<?php

/**
 *
 *  ____                           _   _  ___
 * |  _ \ _ __ ___  ___  ___ _ __ | |_| |/ (_)_ __ ___
 * | |_) | '__/ _ \/ __|/ _ \ '_ \| __| ' /| | '_ ` _ \
 * |  __/| | |  __/\__ \  __/ | | | |_| . \| | | | | | |
 * |_|   |_|  \___||___/\___|_| |_|\__|_|\_\_|_| |_| |_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the MIT License. see <https://opensource.org/licenses/MIT>.
 *
 * @author  PresentKim (debe3721@gmail.com)
 * @link    https://github.com/PresentKim
 * @license https://opensource.org/licenses/MIT MIT License
 *
 *   (\ /)
 *  ( . .) ♥
 *  c(")(")
 *
 * @noinspection PhpUnused
 * @noinspection PhpDocSignatureIsNotCompleteInspection
 * @generated by tools/generate-traits.py - do not edit by hand, edit the spec in that script instead
 */

declare(strict_types=1);

namespace kim\present\lib\arrayutils\traits;

use kim\present\lib\arrayutils\ArrayUtils;
use function array_merge;
use function array_replace_recursive;
use function is_array;

/**
 * Methods that join arrays together (concat, merge, replace, flat)
 *
 * Requires ArrayUtils::toArray(), ArrayUtils::mapToArray(), ArrayUtils::blank() and ArrayUtils::callbackArity() of the class using this trait
 */
trait ConcatTrait{
    /**
     * Merge one or more arrays
     *
     * @link https://arrayutils.docs.present.kim/methods/c/concat
     */
    public function concat(...$values) : ArrayUtils{
        $this->exchangeArray(array_merge($this->getArrayCopy(), ...self::mapToArray($values)));
        return $this;
    }

    /**
     * Same as concat(), but returns a plain array and leaves the instance unchanged
     */
    public function concatAs(...$values) : array{
        return array_merge($this->getArrayCopy(), ...self::mapToArray($values));
    }

    /**
     * Same as concat(), but operates on the given iterable and returns a new ArrayUtils
     */
    public static function concatFrom(iterable $from, ...$values) : ArrayUtils{
        $utils = self::blank();
        $utils->exchangeArray(array_merge((is_array($from) ? $from : self::toArray($from)), ...self::mapToArray($values)));
        return $utils;
    }

    /**
     * Same as concatFrom(), but returns a plain array
     */
    public static function concatFromAs(iterable $from, ...$values) : array{
        return array_merge((is_array($from) ? $from : self::toArray($from)), ...self::mapToArray($values));
    }

    /**
     * All similar to concat(), but not overwrite existing keys
     *
     * @link https://arrayutils.docs.present.kim/methods/c/concat/soft
     */
    public function concatSoft(...$values) : ArrayUtils{
        $this->exchangeArray(self::concatSoftFromAs($this->getArrayCopy(), ...$values));
        return $this;
    }

    /**
     * Same as concatSoft(), but returns a plain array and leaves the instance unchanged
     */
    public function concatSoftAs(...$values) : array{
        return self::concatSoftFromAs($this->getArrayCopy(), ...$values);
    }

    /**
     * Same as concatSoft(), but operates on the given iterable and returns a new ArrayUtils
     */
    public static function concatSoftFrom(iterable $from, ...$values) : ArrayUtils{
        $utils = self::blank();
        $utils->exchangeArray(self::concatSoftFromAs($from, ...$values));
        return $utils;
    }

    /**
     * Same as concatSoftFrom(), but returns a plain array
     */
    public static function concatSoftFromAs(iterable $from, ...$values) : array{
        $array = is_array($from) ? $from : self::toArray($from);
        foreach($values as $value){
            $array += (array) $value;
        }
        return $array;
    }

    /**
     * Alias of concat()
     *
     * @link https://arrayutils.docs.present.kim/methods/c/concat
     */
    public function merge(...$values) : ArrayUtils{
        $this->exchangeArray(array_merge($this->getArrayCopy(), ...self::mapToArray($values)));
        return $this;
    }

    /**
     * Same as merge(), but returns a plain array and leaves the instance unchanged
     */
    public function mergeAs(...$values) : array{
        return array_merge($this->getArrayCopy(), ...self::mapToArray($values));
    }

    /**
     * Same as merge(), but operates on the given iterable and returns a new ArrayUtils
     */
    public static function mergeFrom(iterable $from, ...$values) : ArrayUtils{
        $utils = self::blank();
        $utils->exchangeArray(array_merge((is_array($from) ? $from : self::toArray($from)), ...self::mapToArray($values)));
        return $utils;
    }

    /**
     * Same as mergeFrom(), but returns a plain array
     */
    public static function mergeFromAs(iterable $from, ...$values) : array{
        return array_merge((is_array($from) ? $from : self::toArray($from)), ...self::mapToArray($values));
    }

    /**
     * Alias of concatSoft()
     *
     * @link https://arrayutils.docs.present.kim/methods/c/concat/soft
     */
    public function mergeSoft(...$values) : ArrayUtils{
        $this->exchangeArray(self::mergeSoftFromAs($this->getArrayCopy(), ...$values));
        return $this;
    }

    /**
     * Same as mergeSoft(), but returns a plain array and leaves the instance unchanged
     */
    public function mergeSoftAs(...$values) : array{
        return self::mergeSoftFromAs($this->getArrayCopy(), ...$values);
    }

    /**
     * Same as mergeSoft(), but operates on the given iterable and returns a new ArrayUtils
     */
    public static function mergeSoftFrom(iterable $from, ...$values) : ArrayUtils{
        $utils = self::blank();
        $utils->exchangeArray(self::mergeSoftFromAs($from, ...$values));
        return $utils;
    }

    /**
     * Same as mergeSoftFrom(), but returns a plain array
     */
    public static function mergeSoftFromAs(iterable $from, ...$values) : array{
        $array = is_array($from) ? $from : self::toArray($from);
        return self::concatSoftFromAs($array, ...$values);
    }

    /**
     * Replaces elements from passed arrays into the first array
     *
     * @link https://arrayutils.docs.present.kim/methods/c/replace
     */
    public function replace(iterable ...$iterables) : ArrayUtils{
        $this->exchangeArray(array_replace_recursive($this->getArrayCopy(), ...self::mapToArray($iterables)));
        return $this;
    }

    /**
     * Same as replace(), but returns a plain array and leaves the instance unchanged
     */
    public function replaceAs(iterable ...$iterables) : array{
        return array_replace_recursive($this->getArrayCopy(), ...self::mapToArray($iterables));
    }

    /**
     * Same as replace(), but operates on the given iterable and returns a new ArrayUtils
     */
    public static function replaceFrom(iterable $from, iterable ...$iterables) : ArrayUtils{
        $utils = self::blank();
        $utils->exchangeArray(array_replace_recursive((is_array($from) ? $from : self::toArray($from)), ...self::mapToArray($iterables)));
        return $utils;
    }

    /**
     * Same as replaceFrom(), but returns a plain array
     */
    public static function replaceFromAs(iterable $from, iterable ...$iterables) : array{
        return array_replace_recursive((is_array($from) ? $from : self::toArray($from)), ...self::mapToArray($iterables));
    }

    /**
     * Returns a new array with all sub-array elements concatenated into it recursively up to the specified depth
     *
     * @link https://arrayutils.docs.present.kim/methods/c/flat
     */
    public function flat(int $dept = 1) : ArrayUtils{
        $this->exchangeArray(self::flatFromAs($this->getArrayCopy(), $dept));
        return $this;
    }

    /**
     * Same as flat(), but returns a plain array and leaves the instance unchanged
     */
    public function flatAs(int $dept = 1) : array{
        return self::flatFromAs($this->getArrayCopy(), $dept);
    }

    /**
     * Same as flat(), but operates on the given iterable and returns a new ArrayUtils
     */
    public static function flatFrom(iterable $from, int $dept = 1) : ArrayUtils{
        $utils = self::blank();
        $utils->exchangeArray(self::flatFromAs($from, $dept));
        return $utils;
    }

    /**
     * Same as flatFrom(), but returns a plain array
     */
    public static function flatFromAs(iterable $from, int $dept = 1) : array{
        $array = is_array($from) ? $from : self::toArray($from);
        if($dept <= 0){
            return $array;
        }
        $parts = [];
        foreach($array as $value){
            $parts[] = is_array($value) ? self::flatFromAs($value, $dept - 1) : (array) $value;
        }
        return $parts ? array_merge(...$parts) : [];
    }

    /**
     * Returns a new array formed by applying $callback function and then flattening the result by one level
     *
     * @link https://arrayutils.docs.present.kim/methods/c/flat/map
     */
    public function flatMap(callable $callback) : ArrayUtils{
        $this->exchangeArray(self::flatMapFromAs($this->getArrayCopy(), $callback));
        return $this;
    }

    /**
     * Same as flatMap(), but returns a plain array and leaves the instance unchanged
     */
    public function flatMapAs(callable $callback) : array{
        return self::flatMapFromAs($this->getArrayCopy(), $callback);
    }

    /**
     * Same as flatMap(), but operates on the given iterable and returns a new ArrayUtils
     */
    public static function flatMapFrom(iterable $from, callable $callback) : ArrayUtils{
        $utils = self::blank();
        $utils->exchangeArray(self::flatMapFromAs($from, $callback));
        return $utils;
    }

    /**
     * Same as flatMapFrom(), but returns a plain array
     */
    public static function flatMapFromAs(iterable $from, callable $callback) : array{
        $array = is_array($from) ? $from : self::toArray($from);
        $arity = self::callbackArity($callback);
        if($arity <= 1){
            $parts = [];
            foreach($array as $key => $value){
                $parts[] = (array) $callback($value);
            }
            return $parts ? array_merge(...$parts) : [];
        }
        if($arity <= 2){
            $parts = [];
            foreach($array as $key => $value){
                $parts[] = (array) $callback($value, $key);
            }
            return $parts ? array_merge(...$parts) : [];
        }
        $parts = [];
        foreach($array as $key => $value){
            $parts[] = (array) $callback($value, $key, $array);
        }
        return $parts ? array_merge(...$parts) : [];
    }
}
